### ISSUE TITLE
page-container

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/CV_project#11]
Появился теперь файл `page-container.styl`, который не относится ни к одному блоку. Если это стили для контейнера страницы, то можно из самой страницы и сделать блок index, и все сложить в одну папку. 

Хотя вообще есть ли смысл делать `.page-container`, а потом вкладывать в него `.container`? Один блок с этими задачами не справится? Там у тебя вроде бы только ширина и маржин.

Про маржин отельная тема - по БЭМ маржины не могут устанавливаться блокам, поскольку блок не может влиять на свое окружение, маржины можно добавлять только элементам.

**Comment by viktoriya-ch** [comment]
Про то, как позиционировать блоки, есть в стандартах, шестой пункт
https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md

В твоем случае ты можешь либо самому блоку сделать элемент, например page__content, и задать ему маржины, либо родительскому блоку добавить элемент, внутри которого спозиционировать дочерний блок `page`.

**Comment by imin314** [comment]
Я начала сомневаться что-то... Попробую объяснить сейчас.
Изначально в файле index.pug класс "page-container" использовался для позиционирования блоков "contact", "education", "skills" и т. д. Т. е. сам "page-container" я бы не назвала блоком, поскольку он не соответствует [определению блока в БЭМ](https://ru.bem.info/methodology/key-concepts/#%D0%91%D0%BB%D0%BE%D0%BA): его, конечно, можно использовать повторно, но это будет дублированием целой страницы сайта; ну и никакой другой функции, кроме позиционирования вложенных блоков, у этого класса нет.
Во втором проекте с многостраничным макетом я создавала отдельную папку src/pages, куда складывала pug, js и styl по такой же схеме, как для блоков из папки src/common.blocks.
Может, и тут стоит в src/ оставить только layout.pug, а стиль и шаблон страницы положить в src/pages/index. 
Класс "page-container" (который был в оригинале) я бы переименовала в "index" и положила бы в src/pages/index/styl/index.styl.

**Comment by viktoriya-ch** [comment]
Да, думаю, можно переименовать в index и положить в соответствующую папку. А маржины установить элементом `index__content`, например

**Comment by viktoriya-ch** [comment]
У тебя ведь миксин container больше не используется? Надо его удалить тогда

![Снимок экрана в 2019-09-29 12-31-34](https://user-images.githubusercontent.com/38564412/65830117-23420d00-e2b5-11e9-9e30-c1658d7211f5.png)
