### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/CV_project#12]
Надо добавить `docs` в .gitignore, нет смысла коммитить эту папку, раз она создается автоматически. И коммитить неудобно, и pull делать тоже, потому что эти файлы постоянно мешаются.

**Comment by imin314** [comment]
Поправила. Не знала, что docs автоматически создается

**Comment by imin314** [comment]
А что значит "создается автоматически"?
У меня github pages грузится из папки docs, но если её не коммитить, то ему неоткуда же подтягивать файлы..

**Comment by viktoriya-ch** [comment]
Я немного неправильно выразилась, не автоматически создается, а при сборке проекта у тебя каждый раз эта папка вместе с содержимым генерируется заново. Поэтому можно просто скачать проект с исходниками с гитхаба, собрать, и папка появится, не обязательно ее там хранить, так же как и node modules. 
Чтобы подтягивались файлы для github pages, можно убрать dist в отдельную ветку и указывать ее в настройках github pages. Чтобы это все облегчить, можно, например, использовать плагины.

**Comment by viktoriya-ch** [comment]
Хороший пример того, зачем нужно добавить docs в gitignore - сейчас в этом коммите очень много лишнего: https://github.com/imin314/CV_project/commit/df82849d7ff72ca9e7c9a56d7c011b8479322f0f

**Comment by imin314** [comment]
Ура! Получилось:)
Оказалось, не так сложно. Использовала плагин gh-pages.

**Comment by viktoriya-ch** [comment]
Отлично!)
