### ISSUE TITLE
Параметры

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/CV_project#13]
Мне кажется, лучше всегда хранить параметры в объекте. Со временем параметров может стать больше, потребуется объект, и тогда придется переписывать всё не только в миксине, но и по всему проекту, где он используется.

![Снимок экрана в 2019-09-29 12-39-47](https://user-images.githubusercontent.com/38564412/65830230-3dc8b600-e2b6-11e9-99fe-a0f11ce24c5b.png)

**Comment by imin314** [comment]
Поправила, только забыла сделать коммит и эти правки попали в ишью #4.
Сам коммит: [https://github.com/imin314/CV_project/commit/df82849d7ff72ca9e7c9a56d7c011b8479322f0f](https://github.com/imin314/CV_project/commit/df82849d7ff72ca9e7c9a56d7c011b8479322f0f)
