### ISSUE TITLE
Компонентность, зацепление

### ISSUE THREAD

**Issue by Sergio-Ka** [imin314/CV_project#16]
Компонентная верстка предполагает независимость компонентов друг от друга и еще от чего-нибудь внешнего. При таком подходе, когда они не тянут зависимости со стороны, их легко переиспользовать. У тебя миксин sectionHeader почему-то берет рисунки на стороне в папке assets как будто это общие рисунки, хотя это часть реализации именно этого блока. На сколько тут оправдано применение отдельного миксина roundImage не совсем ясно. Особенно с учетом того, что по большому счету у круглых рисунков данного проекта общее только то, что они круглые (да и то не факт, иконки разделов могут быть квадратными с прозрачным фоном, на которых круглый - сам рисунок). Но зато появляются лишние зависимости, увеличивается зацепление (high coupling), как следствие затрудняется переиспользование, ибо чтобы например использовать sectionHeader компонент на другом проекте, надо будет еще и ему roundImage принести, да еще и в папку assets залезть не забыть. Тут это не выглядит страшным ибо зависимостей мало, но проект учебный - нужно научиться видеть такие вещи. Попробуй на этот предмет критично просмотреть все свои проекты.

**Comment by Sergio-Ka** [comment]
Тут кстати на счет layout.pug - если рассматривать его как компонент и следовать правилам по поводу оформления структуры директорий компонентов о том, что все все реализации компонента должны лежать в одном месте, то возможно тут стоит в папке держать и файлы стилей из файла common.styl.

**Comment by Sergio-Ka** [comment]
И все таки файлы рисунков остались на стороне, вне блока. Это чем-то обосновано?

**Comment by imin314** [comment]
Упустила этот момент сначала. Сейчас перенесла иконки в папку с блоком section-header.

**Comment by imin314** [comment]
То есть выходит, что все изображения должны быть распределены по папкам блоков, в которых они используются?

**Comment by Sergio-Ka** [comment]
Если являются частью реализации блока. То есть эти конкретные картинки используются только в этом блоке и не используются в других блоках - на этом основании и можно сделать вывод, что они являются частью его реализации. Ну а далее в соответствии с методологией БЭМ.
