### ISSUE TITLE
Используй шорткат-свойства

### ISSUE THREAD

**Issue by Sergio-Ka** [imin314/CV_project#18]
Для примера:
```
.round-image
  display inline-block
  width 14.88981537rem
  height 0
  border-width 0.893388922rem 
  padding-bottom @width - (2*@border-width)
  background-color color-main
  border-color #fff
  border-style solid
  border-radius 50%
  box-shadow 0 0 0 2px color-main
```
у тебя здесь для border 3 свойства отдельных, 3 строчки, хотя короткая запись хорошо воспринимается, буков меньше:
border 0.893388922rem solid color-main
То же самое по поводу padding, margin, backgound и т.д. Тут думаю стоит глянуть вообще в проекте и в других проектах тоже.

**Comment by imin314** [comment]
Поправила в этом проекте. Надо еще в остальных исправить.

**Comment by Sergio-Ka** [comment]
` 0.893388922rem` Наверное с такой длинной значения не стоит увлекаться - читается и воспринимается плохо, да и вообще смысла нет больше 2-3 знаков после запятой оставлять. Если это с помощью например расширения к VS Code какому-нибудь делалось из пикселей - то там настроить как правило можно. Тут не критично, но так на будущее думаю стоит обратить внимание.
