### ISSUE TITLE
Респонсивность

### ISSUE THREAD

**Issue by Sergio-Ka** [imin314/CV_project#19]
Не знаю как проект у тебя по факту собирается (не могу собрать, точнее в консоли ошибок нет при сборке, но стили не подтягиваются на странице, соответственно страница вглядит как просто набор текста), но то что лежит в GitHub Pages не соответствует требования по респонсивности.

![image](https://user-images.githubusercontent.com/33621369/66556758-00e4a500-eb7b-11e9-9ead-8a81887dded1.png)

**Comment by imin314** [comment]
Привет! После одной из правок забыла подключить файл с переменными к странице. Сейчас нормально отображается. [commit dfe7414415ea35b5eacec47532e37f15e934e944](https://github.com/imin314/CV_project/commit/dfe7414415ea35b5eacec47532e37f15e934e944)
