### ISSUE TITLE
Проект собирается, но не работает

### ISSUE THREAD

**Issue by Sergio-Ka** [imin314/CV_project#20]
Нужно проверять установку и разворачивание проекта с нуля, это есть среди требований.  Проект собирается без ошибок, но стили к странице собранной не подключены. Что-то с лоадерами что ли или с плагинами.
![image](https://user-images.githubusercontent.com/33621369/66565366-79a02d00-eb8c-11e9-992d-42a84466723e.png)
Проблема с пакетами:
![image](https://user-images.githubusercontent.com/33621369/66565544-f29f8480-eb8c-11e9-8670-bacf6791b639.png)
Так же не понятно в плане сборки проекта - скрипт конкретно для сборки не указан в readme, только девсервер. Не понятно соответствует ли последний проект тому, что лежит на GH Pages, но об этом писал уже в другом issue.

**Comment by imin314** [comment]
Проблема возникала после запуска audit fix. Я его игнорировала, поэтому не заметила сразу.
Сейчас должно нормально работать независимо от audit fix (была проблема с версиями пакетов, поэтому я просто все обновила до последних версий).
Нужно еще раз запустить npm install, чтобы обновились установленные зависимости.

**Comment by imin314** [comment]
Добавила в readme команды для сборки и развертывания проекта. Забыла только отметить эту ишью в комментарии коммита. Вот ссылка:
[commit 7fe3cbcfd7e5715773e13060064f23e29e038f20](https://github.com/imin314/CV_project/commit/7fe3cbcfd7e5715773e13060064f23e29e038f20)

**Comment by Sergio-Ka** [comment]
Ну вот, совсем другое дело.
