### ISSUE TITLE
Импорт стилей

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/CV_project#4]
Нужно сделать автоматический импорт стилей, чтобы не было необходимости при создании / изменении каждого блока прописывать их в style.styl

![Снимок экрана в 2019-09-20 17-52-48](https://user-images.githubusercontent.com/38564412/65336733-92da3d00-dbcf-11e9-8635-7afd43a46e07.png)

**Comment by imin314** [comment]
Добавила автоматический импорт стилей

**Comment by viktoriya-ch** [comment]
В принципе этот вариант рабочий, но есть еще способ через js и он тебе в любом случае во втором проекте пригодится, так как там еще и все js-ки нужно будет импортить автоматом

**Comment by imin314** [comment]
Что-то я в тупике. Нашла способ загружать файлы автоматически с помощью require.context(), но у меня тогда не подгружаются переменные Stylus. В правильном направлении ищу? Или надо через webpack как-то настроить автоматический импорт?

**Comment by imin314** [comment]
Получилось настроить глобальный импорт файла с переменными через настройки webpack.config.js

**Comment by viktoriya-ch** [comment]
Хм, а у тебя нормально проект собирается? У меня сейчас вот такая картина)

![Снимок экрана в 2019-09-26 14-19-55](https://user-images.githubusercontent.com/38564412/65684650-c9e59e00-e068-11e9-98c7-1df7058f794d.png)

**Comment by imin314** [comment]
Это, скорее всего, из-за того что я обновила версию style-loader, когда меняла настройки вебпака.
Дело в том что старая версия не поддерживала функцию:
`injectType: 'singletonStyleTag'`
В package.json версия обновилась, и при повторной установке проекта сборка идет без ошибок.

Дополнительные опции для style-loader оказались не нужны для правильного импорта стилей, так что я могу вернуть назад версию style-loader. Или можешь ты обновить:
`npm i style-loader@1.0.0`

**Comment by viktoriya-ch** [comment]
Хм, нет, все равно то же самое. Попробуй скачать свой проект с гитхаба и запустить его, есть такая ошибка?

**Comment by imin314** [comment]
У меня нормально запускается, даже на другом компе попробовала с гитхаба ставить, и всё нормально работает. А ты пробовала заново с гитхаба установить и всё равно ошибка возникает?

**Comment by viktoriya-ch** [comment]
Так, проблема найдена, вот здесь не хватало точки))

![Снимок экрана в 2019-09-29 11-45-39](https://user-images.githubusercontent.com/38564412/65829474-b9bf0000-e2ae-11e9-9b46-e36d62deef56.png)

**Comment by imin314** [comment]
Кажется, проблема все-таки не в точке. Путь publicPath для devServer должен начинаться с обратного слэша:

![Screenshot_1](https://user-images.githubusercontent.com/40715953/65857855-e8140c80-e38e-11e9-9855-4980bbcd4f63.png)

Точка помогла, потому что из-за ошибки в publicPath файлы подтягивались из папки docs, указанной в contentBase (эта настройка как раз нужна, чтобы указать путь к статическим файлам: [#devservercontentbase](https://webpack.js.org/configuration/dev-server/#devservercontentbase).
Когда я поменяла publicPath на: "./", у меня не было папки docs, и вылезла ошибка.

В общем, я сейчас в publicPath для devServer указала полный путь: publicPath: 'http://localhost:8080/'
Попробуй, пожалуйста, запустить сейчас.
