### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/CV_project#5]
Использование селекторов тэгов противоречит БЭМ, максимум что тут может быть - это стили для html и body, поскольку они уникальны

![Снимок экрана в 2019-09-20 17-50-16](https://user-images.githubusercontent.com/38564412/65336866-c9b05300-dbcf-11e9-9cfb-f783ceeaf3d1.png)

**Comment by viktoriya-ch** [comment]
`Container` у тебя явно блок, а значит нужно создать для него отдельную папку, положить туда миксин pug и стили.

![Снимок экрана в 2019-09-20 18-04-26](https://user-images.githubusercontent.com/38564412/65337662-41cb4880-dbd1-11e9-8a1b-83eb4cad3935.png)

**Comment by imin314** [comment]
Убрала селекторы тэгов и вынесла container в отдельный блок, но нужно еще заново выровнять по Perfect Pixel.
