### ISSUE TITLE
Stylus

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/CV_project#6]
Нужно сделать так, чтобы в файле имя блока встречалось только один раз. То есть не было такого что ты пишешь `circle`, а ниже снова `circle_имя-модификатора`. Так и читается понятнее, и в случае изменения имени блока тебе нужно будет поправить его только в одном месте.

Для обозначения родительского селектора в stylus используется `&`, еще есть способы ссылаться не только на селектор родителя, но и вообще на любые уровни. 

![Снимок экрана в 2019-09-20 18-01-54](https://user-images.githubusercontent.com/38564412/65337421-c36ea680-dbd0-11e9-9b9c-269b71d298aa.png)

**Comment by imin314** [comment]
Поправила глобально в проекте

**Comment by viktoriya-ch** [comment]
И еще немного по единому стилю: сейчас у тебя элементы отбиваются пустой строкой, а модификаторы, псевдоэлементы, псевдоклассы и медиазапросы не отбиваются, мне кажется, было бы логично перед ними тоже оставлять пустую строку

![Снимок экрана в 2019-09-23 15-39-32](https://user-images.githubusercontent.com/38564412/65426175-5cdbc980-de18-11e9-927e-1867f0c3485f.png)
