### ISSUE TITLE
Модификаторы

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/CV_project#8]
Сейчас у тебя в переменных для модификаторов используется конкатенация. По стандартам airbnb конкатенации лучше предпочитать шаблоны строк (https://github.com/airbnb/javascript#es6-template-literals). 

Но в данном случае вообще лучше в миксине хранить объект с доступными модификаторами и проверять, есть ли ключ модификатора, переданный в параметрах, в объекте, если есть - указывать его,  если нет - то указывать дефолтный модификатор. Так будет сразу видно, какие есть доступные модификаторы, которые можно передавать в миксин.

![Снимок экрана в 2019-09-23 16-43-59](https://user-images.githubusercontent.com/38564412/65430916-5ef65600-de21-11e9-805b-a53e28880c5b.png)

**Comment by imin314** [comment]
Добавила проверку, но не уверена, что именно так требовалось поправить. Посмотри, пожалуйста.

**Comment by viktoriya-ch** [comment]
В принципе, рабочее решение, думаю можно так сделать

**Comment by imin314** [comment]
Хочется прийти к единому подходу во всех проектах, поэтому на примере миксина кнопки из второго макета попробовала переписать обработку настроек. Получилось вполне компактно, но правда нарушается правило именования переменных - в настройках, передаваемых в миксин, имена модификаторов следовало бы назвать _isSmall, isResponsive_ и т. д. Или в этом случае допустимо?
![button_screenshot](https://user-images.githubusercontent.com/40715953/65738653-ce639280-e10c-11e9-951a-9e08139bbb92.png)

**Comment by viktoriya-ch** [comment]
Хм, я тут как-то сразу не заметила, пока один модификатор был - удобнее ведь, наверное, хранить в одном объекте группу модификаторов для чего-то одного: цвета, размера и т.д. И в миксин не `true/false` передавать, а например `size: small.` Мне кажется, так будет более систематично, как думаешь?

**Comment by viktoriya-ch** [comment]
И еще по модификаторам: по БЭМ, если модификатор является булевым, то он именуется по правилу `имя-блока_имя-модификатора`, в остальных случаях `имя-блока_имя-модификатора_значение-модификатора`. 

https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80

Например, вот здесь у тебя явно не булевый модификатор, а значит это должно быть ключ-значение

![Снимок экрана в 2019-09-27 16-54-10](https://user-images.githubusercontent.com/38564412/65774724-81e97880-e147-11e9-9c91-737fee91b11e.png)

**Comment by imin314** [comment]
Точно, это правило упустила. Про обработку модификаторов и параметры миксина согласна. Теперь поняла, как нужно сделать.
