### ISSUE TITLE
dotProgressBar

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/CV_project#9]
Название dotProgressBar не очень удачное, а что, если изменится дизайн, и вместо точек будут прямоугольники, например?

Дальше, вот тут в цикле не обязательно указывать фигурные скобки и на каждой строке писать дефис `-`, можно просто отбить строки с телом цикла табами, мне кажется, так будет более читаемо. То есть так же, как и в `each` делать.

![Снимок экрана в 2019-09-23 17-00-04](https://user-images.githubusercontent.com/38564412/65432413-cca38180-de23-11e9-9e21-726e3def1fdb.png)

**Comment by imin314** [comment]
Поправила, но почему-то коммит сюда не попал
_"dotProgressBar renamed to discreteProgressBar + for loop fix #9"_
